### ISSUE TITLE
failed to render and update auto layout status

### ISSUE THREAD

**Issue by MohammedElotol** [stephsharp/MaterialTextField#10]
"failed to render and update auto layout status".
This error message appears when I assign MFTextField class for the UITextField in IB, However, it works but can't be rendered by interface builder.

**Comment by pavlidismi** [comment]
do you find a solution for this ? or maybe something else?

**Comment by stephsharp** [comment]
Hi @MohammedElotol, I've released a new version which includes some updates to the constraints on the text field. Please try the latest version and let me know if you're still having issues with this.

I'm going to close out this issue because it's very old, but if you're still experiencing the same bug on v1.0.1 please raise a new issue and I'll take a look.
